import { useEffect,useMemo,useState } from 'react';
import { Activity,CalendarDays,Check,CheckCircle2,ClipboardList,Clock3,Columns3,Eye,Link2,List,MessageSquare,Plus,Search,ShieldAlert,Sparkles,UserRound,Users,X } from 'lucide-react';
import { useAuth } from '../components/AuthGate';
import { tasksApi,type TaskAssignmentMode,type TaskGroup,type TaskPriority,type TaskStatus,type TaskTargetType,type TaskUser,type TaskWorkflow,type WorkTask } from '../services/tasks';
import '../tasks.css';

const statusLabels:Record<TaskStatus,string>={todo:'Новая',in_progress:'В работе',review:'На проверке',done:'Выполнена',cancelled:'Отменена'};
const priorityLabels:Record<TaskPriority,string>={low:'Низкий',medium:'Обычный',high:'Высокий',urgent:'Срочный'};
const scopes=[{id:'all',label:'Все'},{id:'mine',label:'Мои'},{id:'created',label:'Поставленные мной'},{id:'overdue',label:'Просроченные'},{id:'done',label:'Завершённые'}];
const resultOptions=[['completed','Выполнено'],['contacted','Связались'],['no_answer','Не ответил'],['follow_up','Перезвонить'],['booked','Записался'],['declined','Отказ'],['approved','Согласовано'],['launched','Запущено']];
const taskCode=(task:WorkTask)=>`TASK-${task.id.slice(0,6).toUpperCase()}`;
const resultLabel=(code?:string|null)=>resultOptions.find(([value])=>value===code)?.[1]||code||'—';
const formatDate=(value?:string|null)=>value?new Date(value).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'Без срока';

function slaLabel(task:WorkTask){if(!task.slaDueAt||task.status==='done')return null;const diff=new Date(task.slaDueAt).getTime()-Date.now();const abs=Math.abs(diff);const h=Math.floor(abs/3600000);const m=Math.floor((abs%3600000)/60000);return{breached:diff<0,text:diff<0?`SLA просрочен ${h}ч ${m}м`:`SLA ${h}ч ${m}м`};}

export default function TasksPage(){
 const {user}=useAuth(); const [scope,setScope]=useState('all'); const [tasks,setTasks]=useState<WorkTask[]>([]); const [users,setUsers]=useState<TaskUser[]>([]); const [groups,setGroups]=useState<TaskGroup[]>([]); const [workflows,setWorkflows]=useState<TaskWorkflow[]>([]); const [workflowKey,setWorkflowKey]=useState('general'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<WorkTask|null>(null); const [creating,setCreating]=useState(false); const [view,setView]=useState<'board'|'list'>('board'); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [complete,setComplete]=useState<{task:WorkTask;stageKey?:string}|null>(null);
 const currentWorkflow=workflows.find(w=>w.key===workflowKey)||workflows[0];
 const load=async()=>{setLoading(true);setError(null);try{const [list,boot]=await Promise.all([tasksApi.list(scope,workflowKey),tasksApi.bootstrap()]);setTasks(list.tasks);setUsers(boot.users);setGroups(boot.groups);setWorkflows(boot.workflows);if(selected){const fresh=list.tasks.find(t=>t.id===selected.id);if(fresh)setSelected(fresh);}}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[scope,workflowKey]);
 const visible=useMemo(()=>{const n=query.trim().toLowerCase();return n?tasks.filter(t=>[t.title,t.description,t.createdByName,t.linkLabel,...t.targets.map(x=>x.targetLabel)].filter(Boolean).join(' ').toLowerCase().includes(n)):tasks;},[tasks,query]);
 const replace=(task:WorkTask)=>{setTasks(c=>c.map(x=>x.id===task.id?task:x));setSelected(s=>s?.id===task.id?task:s);};
 const openTask=async(task:WorkTask)=>{setSelected(task);try{const r=await tasksApi.get(task.id);setSelected(r.task);replace(r.task);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}};
 const move=async(task:WorkTask,stageKey:string,resultCode?:string,resultNote?:string)=>{const flow=workflows.find(w=>w.key===task.workflowKey)||currentWorkflow;const stage=flow?.stages.find(s=>s.key===stageKey);if(!stage)return;if(stage.status==='done'&&!resultCode){setComplete({task,stageKey});return;}try{const r=task.assignmentMode==='individual'?await tasksApi.updateExecution(task.id,stage.status,resultCode,resultNote):await tasksApi.update(task.id,{stageKey,resultCode,resultNote});replace(r.task);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}};
 const overdue=tasks.filter(t=>t.dueAt&&new Date(t.dueAt)<new Date()&&!['done','cancelled'].includes(t.status)).length; const slaBreaches=tasks.filter(t=>t.slaDueAt&&new Date(t.slaDueAt)<new Date()&&t.status!=='done').length;
 return <div className="tasks-page">
  <header className="tasks-hero"><div><span className="tasks-eyebrow"><Sparkles size={15}/> IMDS TASKS</span><h1>Задачи</h1><p>Просто видеть, что нужно сделать, кто отвечает и что просрочено.</p></div><button className="button button--primary" onClick={()=>setCreating(true)}><Plus size={17}/>Новая задача</button></header>
  <section className="tasks-kpis"><article><span>Открытые</span><strong>{tasks.filter(t=>!['done','cancelled'].includes(t.status)).length}</strong></article><article><span>Просрочено</span><strong>{overdue}</strong></article><article><span>SLA нарушено</span><strong>{slaBreaches}</strong></article><article><span>Выполнено</span><strong>{tasks.filter(t=>t.status==='done').length}</strong></article></section>
  <section className="tasks-toolbar"><div className="tasks-tabs">{scopes.map(s=><button key={s.id} className={scope===s.id?'active':''} onClick={()=>setScope(s.id)}>{s.label}</button>)}</div><div className="tasks-tools"><select value={workflowKey} onChange={e=>setWorkflowKey(e.target.value)}>{workflows.map(w=><option key={w.key} value={w.key}>{w.name}</option>)}</select><div className="tasks-view-switch"><button className={view==='board'?'active':''} onClick={()=>setView('board')}><Columns3 size={16}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={16}/></button></div><label className="tasks-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск"/></label></div></section>
  {error&&<div className="tasks-error">{error}</div>}
  {loading?<div className="tasks-empty">Загрузка задач…</div>:view==='board'?<section className="tasks-board">{(currentWorkflow?.stages||[]).map(stage=>{const cards=visible.filter(t=>t.stageKey===stage.key||(stage.key==='todo'&&t.stageKey==='accepted'&&!currentWorkflow.stages.some(s=>s.key==='accepted')));return <div className="task-column" key={stage.key} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData('text/task-id');const task=tasks.find(t=>t.id===id);if(task)void move(task,stage.key);}}><header><div><span className={`stage-dot stage-dot--${stage.status}`}/><strong>{stage.name}</strong></div><b>{cards.length}</b></header><div className="task-column-list">{cards.map(task=><TaskCard key={task.id} task={task} onOpen={openTask}/>)}</div></div>;})}</section>:<section className="tasks-list">{visible.map(t=><TaskCard key={t.id} task={t} onOpen={openTask} list/>)}</section>}
  {creating&&<TaskCreateModal users={users} groups={groups} workflows={workflows} initialWorkflow={workflowKey} selfId={user.id} onClose={()=>setCreating(false)} onCreated={task=>{setCreating(false);setWorkflowKey(task.workflowKey);setTasks(c=>[task,...c]);void openTask(task);}}/>}
  {selected&&<TaskDrawer task={selected} workflow={workflows.find(w=>w.key===selected.workflowKey)} currentUserId={user.id} onClose={()=>setSelected(null)} onMove={move} onUpdated={replace}/>} 
  {complete&&<CompleteModal onClose={()=>setComplete(null)} onSubmit={(code,note)=>{const value=complete;setComplete(null);void move(value.task,value.stageKey||'done',code,note);}}/>}
 </div>;
}

function TaskCard({task,onOpen,list=false}:{task:WorkTask;onOpen:(task:WorkTask)=>void;list?:boolean}){const sla=slaLabel(task);const checklist=task.checklist||[];return <button draggable className={`task-card ${list?'task-card--list':''}`} onDragStart={e=>e.dataTransfer.setData('text/task-id',task.id)} onClick={()=>void onOpen(task)}><div className="task-card-top"><span className="task-card-code">{taskCode(task)}</span><span className={`task-priority task-priority--${task.priority}`}>{priorityLabels[task.priority]}</span></div><h3>{task.title}</h3>{task.description&&<p>{task.description}</p>}<div className="task-card-meta"><span><Users size={13}/>{task.targets.map(t=>t.targetLabel).slice(0,2).join(', ')||'Без исполнителя'}</span><span><Clock3 size={13}/>{formatDate(task.dueAt)}</span></div>{sla&&<span className={`task-sla ${sla.breached?'breached':''}`}><ShieldAlert size={12}/>{sla.text}</span>}<div className="task-card-footer"><span>{task.linkLabel&&<><Link2 size={13}/>{task.linkLabel}</>}</span><span>{checklist.length>0&&<><CheckCircle2 size={13}/>{checklist.filter(x=>x.isDone).length}/{checklist.length}</>}</span></div></button>}

function TaskCreateModal({users,groups,workflows,initialWorkflow,selfId,onClose,onCreated}:{users:TaskUser[];groups:TaskGroup[];workflows:TaskWorkflow[];initialWorkflow:string;selfId:string;onClose:()=>void;onCreated:(task:WorkTask)=>void}){
 const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [priority,setPriority]=useState<TaskPriority>('medium');const [dueAt,setDueAt]=useState('');const [mode,setMode]=useState<TaskAssignmentMode>('shared');const [workflowKey,setWorkflowKey]=useState(initialWorkflow);const [slaMinutes,setSlaMinutes]=useState('');const [checklist,setChecklist]=useState('');const [linkLabel,setLinkLabel]=useState('');const [targets,setTargets]=useState<Array<{targetType:TaskTargetType;targetValue?:string;targetLabel:string}>>([]);const [watcherIds,setWatcherIds]=useState<string[]>([]);const [advanced,setAdvanced]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 const add=(target:{targetType:TaskTargetType;targetValue?:string;targetLabel:string})=>setTargets(c=>c.some(x=>x.targetType===target.targetType&&x.targetValue===target.targetValue)?c:[...c,target]);
 const submit=async()=>{if(!title.trim()||!targets.length){setError('Укажите название и исполнителя');return;}setBusy(true);setError(null);try{const r=await tasksApi.create({title:title.trim(),description:description.trim()||null,priority,dueAt:dueAt?new Date(dueAt).toISOString():null,assignmentMode:mode,workflowKey,slaMinutes:Number(slaMinutes)||null,targets,watcherIds,checklist:checklist.split('\n').map(x=>x.trim()).filter(Boolean),linkType:linkLabel?'custom':null,linkLabel:linkLabel||null});onCreated(r.task);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}};
 return <div className="tasks-modal-backdrop"><section className="tasks-modal tasks-create-friendly"><header><div><span className="tasks-modal-kicker">НОВАЯ ЗАДАЧА</span><h2>Что нужно сделать?</h2><p>Сначала только главное. Дополнительные параметры можно открыть ниже.</p></div><button onClick={onClose}><X/></button></header>
  <label className="task-title-field">Название<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Например: Позвонить клиенту и подтвердить запись"/></label>
  <label>Описание <small>необязательно</small><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Коротко объясните, что именно нужно сделать"/></label>
  <div className="tasks-form-grid"><label>Дедлайн<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label>Приоритет<select value={priority} onChange={e=>setPriority(e.target.value as TaskPriority)}>{Object.entries(priorityLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
  <section className="tasks-target-panel tasks-target-panel--compact"><div className="task-section-title"><strong>Кто выполняет</strong><small>Можно выбрать человека, отдел или всех</small></div><div className="tasks-target-actions"><button onClick={()=>add({targetType:'all',targetLabel:'Всем сотрудникам'})}>Всем</button><button onClick={()=>add({targetType:'user',targetValue:selfId,targetLabel:'Себе'})}>Себе</button></div><div className="tasks-target-selects"><select defaultValue="" onChange={e=>{const value=e.target.value;if(!value)return;const group=groups.find(g=>`${g.type}:${g.id}`===value);if(group)add({targetType:group.type,targetValue:group.id,targetLabel:group.name});e.currentTarget.value='';}}><option value="">Выбрать отдел / должность…</option>{groups.map(g=><option key={`${g.type}:${g.id}`} value={`${g.type}:${g.id}`}>{g.name} · {g.memberCount}</option>)}</select><select defaultValue="" onChange={e=>{const person=users.find(u=>u.id===e.target.value);if(person)add({targetType:'user',targetValue:person.id,targetLabel:person.name});e.currentTarget.value='';}}><option value="">Выбрать сотрудника…</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}{u.jobTitle?` · ${u.jobTitle}`:''}</option>)}</select></div><div className="tasks-selected-targets">{targets.length?targets.map((t,i)=><span key={`${t.targetType}:${t.targetValue||i}`}>{t.targetLabel}<button onClick={()=>setTargets(c=>c.filter((_,x)=>x!==i))}>×</button></span>):<small className="task-empty-hint">Исполнитель пока не выбран</small>}</div></section>
  <button className="task-advanced-toggle" onClick={()=>setAdvanced(v=>!v)}>{advanced?'Скрыть дополнительные настройки':'Дополнительно: процесс, SLA, чек-лист и наблюдатели'}</button>
  {advanced&&<div className="task-advanced-panel"><div className="tasks-form-grid"><label>Процесс<select value={workflowKey} onChange={e=>setWorkflowKey(e.target.value)}>{workflows.map(w=><option key={w.key} value={w.key}>{w.name}</option>)}</select></label><label>SLA, минут<input type="number" min="1" value={slaMinutes} onChange={e=>setSlaMinutes(e.target.value)} placeholder="Например: 15"/></label><label>Режим<select value={mode} onChange={e=>setMode(e.target.value as TaskAssignmentMode)}><option value="shared">Одна общая задача</option><option value="individual">Каждому отдельно</option></select></label><label>Связанный объект<input value={linkLabel} onChange={e=>setLinkLabel(e.target.value)} placeholder="Клиент, лид, кампания…"/></label></div><label>Чек-лист <small>по одному пункту на строку</small><textarea rows={4} value={checklist} onChange={e=>setChecklist(e.target.value)} placeholder={'Проверить карточку клиента\nПозвонить\nЗафиксировать результат'}/></label><div className="task-watchers-picker"><strong>Наблюдатели</strong><select defaultValue="" onChange={e=>{const id=e.target.value;if(id&&!watcherIds.includes(id))setWatcherIds(c=>[...c,id]);e.currentTarget.value='';}}><option value="">Добавить наблюдателя…</option>{users.filter(u=>!watcherIds.includes(u.id)).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><div className="tasks-selected-targets">{watcherIds.map(id=>{const person=users.find(u=>u.id===id);return <span key={id}>{person?.name||'Сотрудник'}<button onClick={()=>setWatcherIds(c=>c.filter(x=>x!==id))}>×</button></span>;})}</div></div></div>}
  {error&&<div className="tasks-error">{error}</div>}<footer><button className="button" onClick={onClose}>Отмена</button><button className="button button--primary" disabled={busy} onClick={()=>void submit()}>{busy?'Создаём…':'Создать задачу'}</button></footer>
 </section></div>;
}

function TaskDrawer({task,workflow,currentUserId,onClose,onMove,onUpdated}:{task:WorkTask;workflow?:TaskWorkflow;currentUserId:string;onClose:()=>void;onMove:(task:WorkTask,stageKey:string,resultCode?:string,resultNote?:string)=>Promise<void>;onUpdated:(task:WorkTask)=>void}){
 const [tab,setTab]=useState<'details'|'checklist'|'comments'|'history'>('details');const [comment,setComment]=useState('');const [check,setCheck]=useState('');const [busy,setBusy]=useState(false);const mine=task.executions.find(e=>e.userId===currentUserId);const sla=slaLabel(task);const stage=workflow?.stages.find(s=>s.key===task.stageKey);const stageIndex=workflow?.stages.findIndex(s=>s.key===task.stageKey)??-1;const nextStage=stageIndex>=0?workflow?.stages[stageIndex+1]:undefined;const checklist=task.checklist||[];const doneCount=checklist.filter(x=>x.isDone).length;const assignees=task.targets.map(t=>t.targetLabel).join(', ')||'Без исполнителя';
 const post=async()=>{if(!comment.trim())return;setBusy(true);try{const r=await tasksApi.comment(task.id,comment.trim());setComment('');onUpdated(r.task);}finally{setBusy(false);}};
 const addCheck=async()=>{if(!check.trim())return;const r=await tasksApi.addChecklist(task.id,check.trim());setCheck('');onUpdated(r.task);};
 return <div className="task-drawer-backdrop" onClick={onClose}><aside className="task-drawer task-drawer--friendly" onClick={e=>e.stopPropagation()}>
  <header className="task-friendly-header"><div className="task-friendly-heading"><div className="task-friendly-code-row"><span className="task-code">{taskCode(task)}</span><span>{workflow?.name||'Общие задачи'}</span></div><h2>{task.title}</h2><div className="task-drawer-badges"><span className={`task-priority task-priority--${task.priority}`}>{priorityLabels[task.priority]}</span><span className="task-status-chip">{stage?.name||statusLabels[mine?.status||task.status]}</span>{sla&&<span className={`task-sla ${sla.breached?'breached':''}`}><ShieldAlert size={12}/>{sla.text}</span>}</div></div><button className="task-close" onClick={onClose}><X/></button></header>

  <section className="task-quick-facts"><article><UserRound size={18}/><div><small>Исполнитель</small><strong>{assignees}</strong></div></article><article><CalendarDays size={18}/><div><small>Дедлайн</small><strong>{formatDate(task.dueAt)}</strong></div></article><article><Link2 size={18}/><div><small>Связано</small><strong>{task.linkLabel||'Нет связи'}</strong></div></article><article><Eye size={18}/><div><small>Постановщик</small><strong>{task.createdByName||'Система'}</strong></div></article></section>

  <nav className="task-detail-tabs"><button className={tab==='details'?'active':''} onClick={()=>setTab('details')}><ClipboardList size={15}/>Детали</button><button className={tab==='checklist'?'active':''} onClick={()=>setTab('checklist')}><CheckCircle2 size={15}/>Чек-лист{checklist.length>0&&<b>{doneCount}/{checklist.length}</b>}</button><button className={tab==='comments'?'active':''} onClick={()=>setTab('comments')}><MessageSquare size={15}/>Обсуждение{(task.comments?.length||0)>0&&<b>{task.comments?.length}</b>}</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><Activity size={15}/>История</button></nav>

  <div className="task-detail-body">
   {tab==='details'&&<div className="task-detail-stack"><section className="task-focus-card"><span>ЧТО НУЖНО СДЕЛАТЬ</span><p>{task.description||'Описание не добавлено. Название задачи — основная инструкция.'}</p></section>{task.resultCode&&<section className="task-result-card"><CheckCircle2 size={20}/><div><small>Результат</small><strong>{resultLabel(task.resultCode)}</strong>{task.resultNote&&<p>{task.resultNote}</p>}</div></section>}{task.watchers&&task.watchers.length>0&&<section className="task-simple-section"><h3><Eye size={16}/>Наблюдатели</h3><div className="tasks-selected-targets">{task.watchers.map(w=><span key={w.id}>{w.userName}</span>)}</div></section>}{task.assignmentMode==='individual'&&<section className="task-simple-section"><h3><Users size={16}/>Выполнение команды</h3><div className="task-executions">{task.executions.map(ex=><div key={ex.id}><span>{ex.userName}</span><b>{statusLabels[ex.status]}{ex.resultCode?` · ${resultLabel(ex.resultCode)}`:''}</b></div>)}</div></section>}</div>}

   {tab==='checklist'&&<div className="task-detail-stack"><section className="task-checklist-progress"><div><strong>{checklist.length?Math.round(doneCount/checklist.length*100):0}%</strong><span>{doneCount} из {checklist.length} выполнено</span></div><div className="task-progress-track"><span style={{width:`${checklist.length?doneCount/checklist.length*100:0}%`}}/></div></section><section className="task-simple-section"><div className="task-checklist">{checklist.length?checklist.map(item=><label key={item.id}><input type="checkbox" checked={item.isDone} onChange={async()=>{const r=await tasksApi.toggleChecklist(task.id,item.id,!item.isDone);onUpdated(r.task);}}/><span className={item.isDone?'done':''}>{item.title}</span></label>):<div className="task-empty-state">В этой задаче пока нет чек-листа.</div>}</div><div className="task-inline-add"><input value={check} onChange={e=>setCheck(e.target.value)} placeholder="Добавить пункт"/><button onClick={()=>void addCheck()}><Plus size={16}/></button></div></section></div>}

   {tab==='comments'&&<div className="task-detail-stack"><section className="task-simple-section"><div className="task-comments">{(task.comments||[]).length?(task.comments||[]).map(c=><article key={c.id}><strong>{c.userName}</strong><p>{c.body}</p><small>{new Date(c.createdAt).toLocaleString('ru-RU')}</small></article>):<div className="task-empty-state">Обсуждение ещё не началось.</div>}</div><div className="task-comment-form"><textarea rows={3} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Написать комментарий…"/><button className="button button--primary" disabled={busy||!comment.trim()} onClick={()=>void post()}>Отправить</button></div></section></div>}

   {tab==='history'&&<div className="task-detail-stack"><section className="task-simple-section"><div className="task-history">{(task.history||[]).map(h=><article key={h.id}><span className="history-dot"/><div><strong>{h.actorName}</strong><p>{historyText(h.eventType,h.fromValue,h.toValue)}</p><small>{new Date(h.createdAt).toLocaleString('ru-RU')}</small></div></article>)}</div></section></div>}
  </div>

  <footer className="task-friendly-actions"><label><span>Этап</span><select value={task.stageKey} onChange={e=>void onMove(task,e.target.value)}>{workflow?.stages.map(item=><option key={item.key} value={item.key}>{item.name}</option>)}</select></label>{nextStage&&<button className="button button--primary" onClick={()=>void onMove(task,nextStage.key)}>{nextStage.status==='done'?'Завершить задачу':`Дальше: ${nextStage.name}`}</button>}{!nextStage&&task.status==='done'&&<span className="task-done-label"><Check size={16}/>Задача выполнена</span>}</footer>
 </aside></div>;
}

function historyText(type:string,from?:string|null,to?:string|null){if(type==='created')return 'создал задачу';if(type==='stage_changed')return `изменил этап: ${from||'—'} → ${to||'—'}`;if(type==='status_changed'||type==='execution_status')return `изменил статус: ${to||'—'}`;if(type==='commented')return 'добавил комментарий';if(type==='checklist_added')return `добавил пункт: ${to||''}`;if(type==='checklist_toggled')return 'обновил чек-лист';return 'обновил задачу';}
function CompleteModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:(code:string,note:string)=>void}){const [code,setCode]=useState('completed');const [note,setNote]=useState('');return <div className="tasks-modal-backdrop"><section className="tasks-modal tasks-complete-modal"><header><div><span className="tasks-modal-kicker">ЗАВЕРШЕНИЕ</span><h2>Какой результат?</h2><p>Зафиксируйте итог — это займёт несколько секунд.</p></div><button onClick={onClose}><X/></button></header><label>Результат<select value={code} onChange={e=>setCode(e.target.value)}>{resultOptions.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Комментарий <small>необязательно</small><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Коротко: что произошло?"/></label><footer><button className="button" onClick={onClose}>Отмена</button><button className="button button--primary" onClick={()=>onSubmit(code,note)}><Check size={16}/>Готово</button></footer></section></div>}
