import { useEffect, useMemo, useState } from 'react';
import { Bar, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ChevronDown, ChevronRight, Filter, RefreshCw, SlidersHorizontal, X } from 'lucide-react';

type Campaign={key:string;platform:string;source:string;campaign_id:string;campaign_name:string;utm_source:string;utm_medium:string;utm_campaign:string;spend:number;revenue:number;impressions:number;reach:number;clicks:number;ads_leads:number;crm_leads:number;target_leads:number;in_work:number;rejected:number;appointments:number;arrived:number;deals_in_work:number;deals_rejected:number;sales:number;roas:number;cpl:number;cpm:number;ctr:number;link_ctr:number;frequency:number;recommendation:string};
type Platform={platform:string;campaigns:number;spend:number;revenue:number;leads:number;target_leads:number;arrived:number;sales:number;impressions:number;roas:number;sale_rate:number};
type Data={period:{from:string;to:string};totals:{leads:number;target_leads:number;arrived:number;sales:number;spend:number;revenue:number};daily:Array<{date:string;leads:number;sales:number;spend:number}>;platforms:Platform[];campaigns:Campaign[];hourly:Array<{hour:number;leads:number;appointments:number;rate:number}>;weekdays:Array<{day:number;appointments:number;rate:number}>;delays:Array<{day:number;appointments:number;rate:number}>;attribution:{unattributed_leads:number;unattributed_rate:number}};
const empty:Data={period:{from:'',to:''},totals:{leads:0,target_leads:0,arrived:0,sales:0,spend:0,revenue:0},daily:[],platforms:[],campaigns:[],hourly:[],weekdays:[],delays:[],attribution:{unattributed_leads:0,unattributed_rate:0}};
const money=(v:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'KZT',maximumFractionDigits:0}).format(v||0);
const num=(v:number)=>new Intl.NumberFormat('ru-RU').format(v||0);
const pct=(v:number,t:number)=>t?`${Math.round(v*100/t)}%`:'0%';
const colors=['#2563eb','#ec4899','#f97316','#0ea5e9','#22c55e','#14b8a6','#8b5cf6'];
const week=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];

export default function V36Dashboard(){
 const[days,setDays]=useState(7),[data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[mode,setMode]=useState<'ads'|'crm'>('ads'),[open,setOpen]=useState<Record<string,boolean>>({}),[sourceMenu,setSourceMenu]=useState(false),[sources,setSources]=useState<string[]>([]),[utm,setUtm]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/analytics/overview?days=${days}`),text=await r.text();if(!r.ok)throw new Error(text||`HTTP ${r.status}`);setData(JSON.parse(text));}catch(e){setError(e instanceof Error?e.message:String(e));setData(empty);}finally{setLoading(false)}};
 useEffect(()=>{void load()},[days]);
 const sourceOptions=useMemo(()=>Array.from(new Set(data.campaigns.map(x=>x.source||x.platform).filter(Boolean))),[data]);
 const filtered=useMemo(()=>data.campaigns.filter(x=>(!sources.length||sources.includes(x.source||x.platform))&&(!utm||[x.utm_source,x.utm_medium,x.utm_campaign,x.campaign_name].some(v=>(v||'').toLowerCase().includes(utm.toLowerCase())))),[data,sources,utm]);
 const grouped=useMemo(()=>data.platforms.map(p=>({p,rows:filtered.filter(x=>x.platform===p.platform)})),[data,filtered]);
 const chart=data.daily.map(x=>({...x,label:new Date(`${x.date}T00:00:00`).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'})}));
 const t=data.totals;
 return <main className="v36-dashboard">
  <section className="v36-toolbar"><div className="v36-periods">{[3,7,15,30].map(v=><button key={v} className={days===v?'active':''} onClick={()=>setDays(v)}>{v} {v===3?'дня':'дней'}</button>)}</div><div className="v36-filter"><button className={sources.length?'active':''} onClick={()=>setSourceMenu(!sourceMenu)}><Filter size={14}/>Источники{sources.length?` (${sources.length})`:''}<ChevronDown size={14}/></button>{sourceMenu&&<div className="v36-popover">{sourceOptions.map(s=><label key={s}><input type="checkbox" checked={sources.includes(s)} onChange={()=>setSources(p=>p.includes(s)?p.filter(x=>x!==s):[...p,s])}/>{s}</label>)}</div>}</div><label className="v36-search"><SlidersHorizontal size={14}/><input value={utm} onChange={e=>setUtm(e.target.value)} placeholder="UTM source / medium / campaign"/></label>{(sources.length>0||utm)&&<button className="v36-reset" onClick={()=>{setSources([]);setUtm('')}}><X size={13}/>Сбросить</button>}<span>{data.period.from||'—'} — {data.period.to||'—'}</span><button className="v36-sync" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?'spin':''} size={14}/>Обновить</button></section>
  {error&&<div className="v36-error">{error}</div>}
  <section className="v36-kpis">{[
   ['Всего лидов',num(t.leads),'Лиды CRM','blue'],['Целевые лиды',num(t.target_leads),`${pct(t.target_leads,t.leads)} от всех`,'cyan'],['Пришли',num(t.arrived),`${pct(t.arrived,t.target_leads)} от целевых`,'purple'],['Продажи',num(t.sales),`${pct(t.sales,t.arrived)} от пришедших`,'green'],['Выручка',money(t.revenue),`Средний чек ${money(t.sales?t.revenue/t.sales:0)}`,'amber'],['Расход',money(t.spend),`ROAS ${t.spend?(t.revenue/t.spend).toFixed(1):'0'}x`,'violet'],['Неатрибутированные',`${data.attribution.unattributed_rate.toFixed(1)}%`,`${num(data.attribution.unattributed_leads)} лидов`,'red']
  ].map(([a,b,c,d])=><article className={`v36-kpi tone-${d}`} key={a}><i/><strong>{b}</strong><span>{a}</span><small>{c}</small></article>)}</section>
  <section className="v36-card"><header><div><h2>Динамика лидов</h2><p>Лиды, WON и рекламный расход</p></div></header><div className="v36-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart}><CartesianGrid stroke="#1e2d4a" vertical={false}/><XAxis dataKey="label" stroke="#64748b"/><YAxis yAxisId="l" stroke="#64748b"/><YAxis yAxisId="r" orientation="right" stroke="#64748b"/><Tooltip contentStyle={{background:'#060c1c',border:'1px solid #1e2d4a'}}/><Bar yAxisId="r" dataKey="spend" fill="#1e3a5f"/><Line yAxisId="l" dataKey="leads" stroke="#2563eb" strokeWidth={3}/><Line yAxisId="l" dataKey="sales" stroke="#22c55e" strokeWidth={3}/></ComposedChart></ResponsiveContainer></div></section>
  <section className="v36-summary"><article className="v36-card"><h2>Источники</h2><div className="v36-pie"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.platforms} dataKey="leads" nameKey="platform" innerRadius={52} outerRadius={78}>{data.platforms.map((p,i)=><Cell key={p.platform} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div>{data.platforms.map((p,i)=><p className="v36-source" key={p.platform}><i style={{background:colors[i%colors.length]}}/><b>{p.platform}</b><strong>{num(p.leads)}</strong><span>{pct(p.leads,t.leads)}</span></p>)}</article><article className="v36-card"><h2>Расход и ROAS</h2>{data.platforms.map((p,i)=><div className="v36-bar" key={p.platform}><p><b>{p.platform}</b><span>{money(p.spend)} · {p.roas.toFixed(1)}x</span></p><i><em style={{width:`${t.spend?Math.max(2,p.spend/t.spend*100):0}%`,background:colors[i%colors.length]}}/></i></div>)}</article><article className="v36-card"><h2>Воронка</h2>{data.platforms.map((p,i)=><div className="v36-bar" key={p.platform}><p><b>{p.platform}</b><span>{num(p.sales)} / {num(p.leads)} · {Math.round(p.sale_rate)}%</span></p><i><em style={{width:`${Math.max(2,p.sale_rate)}%`,background:colors[i%colors.length]}}/></i></div>)}</article></section>
  <section className="v36-card v36-table-card"><header><div><h2>Детализация по кампаниям</h2><p>{filtered.length} кампаний</p></div><div className="v36-mode"><button className={mode==='ads'?'active':''} onClick={()=>setMode('ads')}>Реклама</button><button className={mode==='crm'?'active':''} onClick={()=>setMode('crm')}>CRM-воронка</button></div></header><div className="v36-table"><table><thead>{mode==='ads'?<tr><th>Источник / кампания</th><th>UTM source</th><th>UTM medium</th><th>UTM campaign</th><th>ROAS</th><th>Расход</th><th>Выручка</th><th>Показы</th><th>Охват</th><th>Клики</th><th>CTR</th><th>CPM</th><th>Частота</th><th>Рекомендация</th></tr>:<tr><th>Источник / кампания</th><th>CPL</th><th>Лиды рекламы</th><th>Лиды CRM</th><th>Целевые</th><th>В работе</th><th>Брак</th><th>Записаны</th><th>Пришли</th><th>Купили</th><th>Конверсия</th></tr>}</thead><tbody>{grouped.map(g=><>{<tr className="v36-group" key={g.p.platform} onClick={()=>setOpen(p=>({...p,[g.p.platform]:!p[g.p.platform]}))}><td><ChevronRight className={open[g.p.platform]?'open':''} size={14}/><b>{g.p.platform}</b><small>{g.rows.length} кампаний</small></td>{mode==='ads'?<><td/><td/><td/><td>{g.p.roas.toFixed(1)}x</td><td>{money(g.p.spend)}</td><td>{money(g.p.revenue)}</td><td>{num(g.p.impressions)}</td><td/><td/><td/><td/><td/><td/></>:<><td>{money(g.p.leads?g.p.spend/g.p.leads:0)}</td><td/><td>{num(g.p.leads)}</td><td>{num(g.p.target_leads)}</td><td/><td/><td/><td>{num(g.p.arrived)}</td><td>{num(g.p.sales)}</td><td>{pct(g.p.sales,g.p.leads)}</td></>}</tr>}{open[g.p.platform]&&g.rows.map(r=><tr key={r.key}><td><b>{r.campaign_name||r.source}</b><small>{r.campaign_id||r.source}</small></td>{mode==='ads'?<><td>{r.utm_source||'—'}</td><td>{r.utm_medium||'—'}</td><td>{r.utm_campaign||'—'}</td><td>{r.roas.toFixed(1)}x</td><td>{money(r.spend)}</td><td>{money(r.revenue)}</td><td>{num(r.impressions)}</td><td>{num(r.reach)}</td><td>{num(r.clicks)}</td><td>{r.ctr.toFixed(1)}%</td><td>{money(r.cpm)}</td><td>{r.frequency.toFixed(1)}</td><td>{r.recommendation||'Наблюдать'}</td></>:<><td>{money(r.cpl)}</td><td>{num(r.ads_leads)}</td><td>{num(r.crm_leads)}</td><td>{num(r.target_leads)}</td><td>{num(r.in_work)}</td><td>{num(r.rejected)}</td><td>{num(r.appointments)}</td><td>{num(r.arrived)}</td><td>{num(r.sales)}</td><td>{pct(r.sales,r.crm_leads)}</td></>}</tr>)}</>)}</tbody></table></div></section>
  <section className="v36-heats"><article className="v36-card"><h2>По часам</h2>{data.hourly.map(r=><p key={r.hour}><b>{String(r.hour).padStart(2,'0')}:00</b><span>{num(r.leads)} лидов</span><em>{r.rate.toFixed(1)}%</em></p>)}</article><article className="v36-card"><h2>По дням недели</h2>{data.weekdays.map(r=><p key={r.day}><b>{week[r.day]||week[r.day-1]||r.day}</b><span>{num(r.appointments)} записей</span><em>{r.rate.toFixed(1)}%</em></p>)}</article><article className="v36-card"><h2>Задержка до записи</h2>{data.delays.map(r=><p key={r.day}><b>{r.day} день</b><span>{num(r.appointments)} записей</span><em>{r.rate.toFixed(1)}%</em></p>)}</article></section>
 </main>
}
