import { resolveCompanyId } from './companyContext';
import { listActiveCompanyUsers } from './companyUsers';
import type { Env } from './integrations';

type Row = Record<string, unknown>;
const text=(v:unknown)=>typeof v==='string'?v.trim():'';
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const userId=(r:Request)=>text(r.headers.get('x-amanat-auth-user'));
function headers(env:Env,extra:HeadersInit={}):HeadersInit{return{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json',...extra};}
async function db<T>(env:Env,path:string,init:RequestInit={}):Promise<T>{const response=await fetch(`${env.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/${path}`,{...init,headers:headers(env,init.headers)});const body=await response.text();if(!response.ok)throw new Error(`Task notifications ${response.status}: ${body.slice(0,700)}`);return(body?JSON.parse(body):null) as T;}
async function activeUsers(env:Env,companyId:string){const users=await listActiveCompanyUsers(env,companyId,'id,name');const assignments=await db<Row[]>(env,`crm_access_user_assignments?company_id=eq.${companyId}&select=user_id,position_id,job_title`);const map=new Map(assignments.map(r=>[text(r.user_id),r]));return users.map(r=>{const a=map.get(text(r.id))||{};return{id:text(r.id),positionId:text(a.position_id)||null,jobTitle:text(a.job_title)||null};});}
async function targetRecipients(env:Env,companyId:string,taskId:string){const [users,targets]=await Promise.all([activeUsers(env,companyId),db<Row[]>(env,`crm_task_targets?company_id=eq.${companyId}&task_id=eq.${taskId}&select=target_type,target_value`)]);const ids=new Set<string>();for(const t of targets){const type=text(t.target_type),value=text(t.target_value);if(type==='all')users.forEach(u=>ids.add(u.id));if(type==='user'&&users.some(u=>u.id===value))ids.add(value);if(type==='position')users.filter(u=>u.positionId===value).forEach(u=>ids.add(u.id));if(type==='job_title')users.filter(u=>u.jobTitle===value).forEach(u=>ids.add(u.id));}return[...ids];}
async function insertMany(env:Env,rows:Row[]){if(!rows.length)return;await db(env,'crm_task_notifications?on_conflict=company_id,user_id,task_id,kind,dedupe_key',{method:'POST',headers:{prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify(rows)});}
export async function createAssignedNotifications(env:Env,companyId:string,taskId:string,title:string,recipients:string[],dueAt?:unknown){const due=text(dueAt);await insertMany(env,recipients.map(id=>({company_id:companyId,user_id:id,task_id:taskId,kind:'assigned',title:'Новая задача',message:due?`${title} · срок ${new Date(due).toLocaleString('ru-RU')}`:title,dedupe_key:'assigned'})));}
export async function runTaskNotificationScan(env:Env){const now=Date.now(),soon=now+24*60*60*1000;const tasks=await db<Row[]>(env,'crm_tasks?due_at=not.is.null&status=not.in.(done,cancelled)&select=id,company_id,title,due_at,assignment_mode&limit=5000');let created=0;for(const task of tasks){const due=Date.parse(text(task.due_at));if(!Number.isFinite(due)||due>soon)continue;const companyId=text(task.company_id),taskId=text(task.id),title=text(task.title);let recipients:string[]=[];if(text(task.assignment_mode)==='individual'){const rows=await db<Row[]>(env,`crm_task_executions?company_id=eq.${companyId}&task_id=eq.${taskId}&status=not.in.(done,cancelled)&select=user_id`);recipients=rows.map(r=>text(r.user_id)).filter(Boolean);}else recipients=await targetRecipients(env,companyId,taskId);const kind=due<now?'overdue':'due_soon';const label=kind==='overdue'?'Задача просрочена':'Срок задачи приближается';const key=kind==='overdue'?'overdue':`due:${text(task.due_at)}`;const rows=recipients.map(id=>({company_id:companyId,user_id:id,task_id:taskId,kind,title:label,message:`${title} · срок ${new Date(due).toLocaleString('ru-RU')}`,dedupe_key:key}));await insertMany(env,rows);created+=rows.length;}return{ok:true,processed:tasks.length,candidates:created};}
export async function handleTaskNotifications(request:Request,env:Env,url:URL):Promise<Response|null>{if(!url.pathname.startsWith('/api/task-notifications'))return null;try{const id=userId(request);if(!id)return json({error:'Unauthorized'},401);const companyId=await resolveCompanyId(env,id);if(url.pathname==='/api/task-notifications'&&request.method==='GET'){const rows=await db<Row[]>(env,`crm_task_notifications?company_id=eq.${companyId}&user_id=eq.${id}&select=*&order=created_at.desc&limit=100`);return json({notifications:rows.map(r=>({id:r.id,taskId:r.task_id,kind:r.kind,title:r.title,message:r.message,readAt:r.read_at,createdAt:r.created_at})),unread:rows.filter(r=>!r.read_at).length});}if(url.pathname==='/api/task-notifications/read-all'&&request.method==='PATCH'){await db(env,`crm_task_notifications?company_id=eq.${companyId}&user_id=eq.${id}&read_at=is.null`,{method:'PATCH',headers:{prefer:'return=minimal'},body:JSON.stringify({read_at:new Date().toISOString()})});return json({ok:true});}const match=url.pathname.match(/^\/api\/task-notifications\/([0-9a-f-]+)\/read$/i);if(match&&request.method==='PATCH'){await db(env,`crm_task_notifications?id=eq.${match[1]}&company_id=eq.${companyId}&user_id=eq.${id}`,{method:'PATCH',headers:{prefer:'return=minimal'},body:JSON.stringify({read_at:new Date().toISOString()})});return json({ok:true});}return json({error:'Method not allowed'},405);}catch(error){return json({error:error instanceof Error?error.message:String(error)},500);}}
