import { resolveCompanyId } from './companyContext';
import { listActiveCompanyUsers } from './companyUsers';
import type { Env } from './integrations';

type Row = Record<string, unknown>;
class ActionError extends Error { constructor(readonly status:number,message:string){super(message);} }
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const record=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:{};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function headers(env:Env,extra:HeadersInit={}):HeadersInit{return{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json',...(extra as Record<string,string>)};}
async function db<T>(env:Env,path:string,init:RequestInit={}):Promise<T>{const response=await fetch(`${env.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/${path}`,{...init,headers:headers(env,init.headers||{})});const body=await response.text();if(!response.ok)throw new ActionError(502,`Task action database ${response.status}: ${body.slice(0,500)}`);return(body?JSON.parse(body):null)as T;}
async function context(request:Request,env:Env){const id=text(request.headers.get('x-amanat-auth-user'));if(!uuid.test(id))throw new ActionError(401,'Не удалось определить пользователя');const requested=text(request.headers.get('x-imds-company-id'));const scoped=requested?{...env,CURRENT_COMPANY_ID:requested}:env;return{companyId:await resolveCompanyId(scoped,id),userId:id,role:text(request.headers.get('x-amanat-auth-role'))};}
async function canAct(env:Env,companyId:string,userId:string,task:Row){if(text(task.created_by)===userId)return true;const users=await listActiveCompanyUsers(env,companyId,'id,name,email');if(!users.some(u=>text(u.id)===userId))return false;const [assignmentRows,targets,execution]=await Promise.all([db<Row[]>(env,`crm_access_user_assignments?company_id=eq.${companyId}&user_id=eq.${userId}&select=position_id,job_title&limit=1`),db<Row[]>(env,`crm_task_targets?company_id=eq.${companyId}&task_id=eq.${text(task.id)}&select=target_type,target_value`),db<Row[]>(env,`crm_task_executions?company_id=eq.${companyId}&task_id=eq.${text(task.id)}&user_id=eq.${userId}&select=id&limit=1`)]);if(execution[0])return true;const assignment=assignmentRows[0]||{};return targets.some(target=>{const type=text(target.target_type);const value=text(target.target_value);return type==='all'||(type==='user'&&value===userId)||(type==='position'&&value===text(assignment.position_id))||(type==='job_title'&&value===text(assignment.job_title));});}
export async function handleTaskQuickActions(request:Request,env:Env,url:URL):Promise<Response|null>{if(url.pathname!=='/api/tasks/suite/postpone')return null;try{if(request.method!=='POST')return json({error:'Method not allowed'},405);const ctx=await context(request,env);const input=record(await request.json().catch(()=>({})));const taskId=text(input.taskId);if(!uuid.test(taskId))throw new ActionError(400,'Некорректная задача');const rows=await db<Row[]>(env,`crm_tasks?company_id=eq.${ctx.companyId}&id=eq.${taskId}&source=eq.work_tasks&select=*&limit=1`);const task=rows[0];if(!task)throw new ActionError(404,'Задача не найдена');if(ctx.role!=='administrator'&&!(await canAct(env,ctx.companyId,ctx.userId,task)))throw new ActionError(403,'Эта задача не назначена вам');if(['done','cancelled'].includes(text(task.status)))throw new ActionError(400,'Завершённую задачу нельзя переносить');const requested=text(input.dueAt);const current=task.due_at?new Date(String(task.due_at)):new Date();const dueAt=requested?new Date(requested):new Date(current.getTime()+86400000);if(Number.isNaN(dueAt.getTime()))throw new ActionError(400,'Некорректный срок');const updated=await db<Row[]>(env,`crm_tasks?company_id=eq.${ctx.companyId}&id=eq.${taskId}`,{method:'PATCH',headers:{prefer:'return=representation'},body:JSON.stringify({due_at:dueAt.toISOString(),updated_at:new Date().toISOString()})});await db(env,'crm_task_history',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify({company_id:ctx.companyId,task_id:taskId,actor_id:ctx.userId,event_type:'due_postponed',from_value:task.due_at||null,to_value:dueAt.toISOString()})});return json({taskId,task:updated[0]||null,dueAt:dueAt.toISOString()});}catch(error){if(error instanceof ActionError)return json({error:error.message},error.status);return json({error:error instanceof Error?error.message:String(error)},500);}}
