import { resolveCompanyId } from './companyContext';
import { listActiveCompanyUsers } from './companyUsers';
import type { Env } from './integrations';

type Row = Record<string, unknown>;
class HttpError extends Error { constructor(readonly status:number,message:string){super(message);} }
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const record=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:{};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const statuses=['todo','in_progress','review','done','cancelled']; const priorities=['low','medium','high','urgent'];
const userId=(request:Request)=>text(request.headers.get('x-amanat-auth-user')); const role=(request:Request)=>text(request.headers.get('x-amanat-auth-role'));
function headers(env:Env,extra:HeadersInit={}):HeadersInit{return{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json',...extra};}
async function db<T>(env:Env,path:string,init:RequestInit={}):Promise<T>{const response=await fetch(`${env.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/${path}`,{...init,headers:headers(env,init.headers)});const body=await response.text();if(!response.ok)throw new HttpError(502,`Tasks database ${response.status}: ${body.slice(0,800)}`);return(body?JSON.parse(body):null)as T;}
async function context(request:Request,env:Env){const id=userId(request);if(!uuid.test(id))throw new HttpError(401,'Не удалось определить пользователя');const companyId=await resolveCompanyId(env,id);return{companyId,userId:id,role:role(request)};}
async function activeUsers(env:Env,companyId:string){const users=await listActiveCompanyUsers(env,companyId,'id,name,email');const assignments=await db<Row[]>(env,`crm_access_user_assignments?company_id=eq.${companyId}&select=user_id,position_id,job_title`);const positions=await db<Row[]>(env,`crm_access_positions?company_id=eq.${companyId}&select=id,name`);const aMap=new Map(assignments.map(row=>[text(row.user_id),row]));const pMap=new Map(positions.map(row=>[text(row.id),text(row.name)]));return users.map(row=>{const a=aMap.get(text(row.id))||{};return{id:text(row.id),name:text(row.name),email:text(row.email),positionId:text(a.position_id)||null,positionName:pMap.get(text(a.position_id))||null,jobTitle:text(a.job_title)||null};});}
async function bootstrap(env:Env,companyId:string){const users=await activeUsers(env,companyId);const groups=new Map<string,{id:string;name:string;type:'position'|'job_title';memberCount:number}>();for(const u of users){if(u.positionId&&u.positionName){const key=`position:${u.positionId}`;const g=groups.get(key)||{id:u.positionId,name:u.positionName,type:'position' as const,memberCount:0};g.memberCount++;groups.set(key,g);}if(u.jobTitle){const key=`job:${u.jobTitle}`;const g=groups.get(key)||{id:u.jobTitle,name:u.jobTitle,type:'job_title' as const,memberCount:0};g.memberCount++;groups.set(key,g);}}return{users,groups:[...groups.values()]};}
async function hydrate(env:Env,companyId:string,tasks:Row[],includeComments=false){if(!tasks.length)return[];const taskIds=tasks.map(r=>text(r.id)).filter(Boolean);const userIds=new Set<string>();tasks.forEach(r=>{const id=text(r.created_by);if(id)userIds.add(id);});const [targets,executions,comments,users] = await Promise.all([
 db<Row[]>(env,`crm_task_targets?company_id=eq.${companyId}&task_id=in.(${taskIds.join(',')})&select=*`),
 db<Row[]>(env,`crm_task_executions?company_id=eq.${companyId}&task_id=in.(${taskIds.join(',')})&select=*`),
 includeComments?db<Row[]>(env,`crm_task_comments?company_id=eq.${companyId}&task_id=in.(${taskIds.join(',')})&select=*&order=created_at.asc`):Promise.resolve([] as Row[]),
 activeUsers(env,companyId)
]);executions.forEach(r=>userIds.add(text(r.user_id)));comments.forEach(r=>userIds.add(text(r.user_id)));const uMap=new Map(users.map(u=>[u.id,u.name]));
return tasks.map(r=>({id:text(r.id),title:text(r.title),description:r.description||null,status:text(r.status)||'todo',priority:text(r.priority)||'medium',dueAt:r.due_at||null,completedAt:r.completed_at||null,createdAt:r.created_at,updatedAt:r.updated_at,createdBy:r.created_by||null,createdByName:uMap.get(text(r.created_by))||null,assignmentMode:text(r.assignment_mode)==='individual'?'individual':'shared',targets:targets.filter(t=>text(t.task_id)===text(r.id)).map(t=>({id:text(t.id),targetType:text(t.target_type),targetValue:t.target_value||null,targetLabel:text(t.target_label)})),executions:executions.filter(e=>text(e.task_id)===text(r.id)).map(e=>({id:text(e.id),userId:text(e.user_id),userName:uMap.get(text(e.user_id))||'Сотрудник',status:text(e.status)||'todo',completedAt:e.completed_at||null,updatedAt:e.updated_at})),comments:comments.filter(c=>text(c.task_id)===text(r.id)).map(c=>({id:text(c.id),userId:text(c.user_id),userName:uMap.get(text(c.user_id))||'Сотрудник',body:text(c.body),createdAt:c.created_at}))}));}
async function resolveTargetUsers(env:Env,companyId:string,targets:Row[]){const users=await activeUsers(env,companyId);const ids=new Set<string>();for(const t of targets){const type=text(t.targetType||t.target_type);const value=text(t.targetValue||t.target_value);if(type==='all')users.forEach(u=>ids.add(u.id));if(type==='user'&&uuid.test(value)&&users.some(u=>u.id===value))ids.add(value);if(type==='position')users.filter(u=>u.positionId===value).forEach(u=>ids.add(u.id));if(type==='job_title')users.filter(u=>u.jobTitle===value).forEach(u=>ids.add(u.id));}return[...ids];}
async function canManage(request:Request){return role(request)==='administrator';}
async function recipientUserIds(env:Env,companyId:string,taskId:string){const targets=await db<Row[]>(env,`crm_task_targets?company_id=eq.${companyId}&task_id=eq.${taskId}&select=target_type,target_value,target_label`);return resolveTargetUsers(env,companyId,targets);}
async function readTask(env:Env,companyId:string,id:string){const rows=await db<Row[]>(env,`crm_tasks?company_id=eq.${companyId}&id=eq.${id}&select=*&limit=1`);if(!rows[0])throw new HttpError(404,'Задача не найдена');return rows[0];}
async function list(request:Request,env:Env,url:URL){const ctx=await context(request,env);const scope=url.searchParams.get('scope')||'all';let filter=`company_id=eq.${ctx.companyId}`;if(scope==='created')filter+=`&created_by=eq.${ctx.userId}`;if(scope==='done')filter+=`&status=eq.done`;if(scope==='overdue')filter+=`&due_at=lt.${encodeURIComponent(new Date().toISOString())}&status=not.in.(done,cancelled)`;let tasks=await db<Row[]>(env,`crm_tasks?${filter}&select=*&order=created_at.desc&limit=500`);let hydrated=await hydrate(env,ctx.companyId,tasks,false);if(scope==='mine'){const mine=new Set((await db<Row[]>(env,`crm_task_executions?company_id=eq.${ctx.companyId}&user_id=eq.${ctx.userId}&select=task_id`)).map(r=>text(r.task_id)));const recipients=await activeUsers(env,ctx.companyId);const me=recipients.find(u=>u.id===ctx.userId);hydrated=hydrated.filter((task:any)=>mine.has(task.id)||task.targets.some((t:any)=>t.targetType==='all'||(t.targetType==='user'&&t.targetValue===ctx.userId)||(t.targetType==='position'&&me?.positionId===t.targetValue)||(t.targetType==='job_title'&&me?.jobTitle===t.targetValue)));}return json({tasks:hydrated});}
async function create(request:Request,env:Env){const ctx=await context(request,env);const input=record(await request.json().catch(()=>({})));const title=text(input.title);if(title.length<2)throw new HttpError(400,'Укажите название задачи');const priority=text(input.priority)||'medium';if(!priorities.includes(priority))throw new HttpError(400,'Некорректный приоритет');const assignmentMode=text(input.assignmentMode)==='individual'?'individual':'shared';const rawTargets=Array.isArray(input.targets)?input.targets.map(record):[];if(!rawTargets.length)throw new HttpError(400,'Выберите адресатов');const created=await db<Row[]>(env,'crm_tasks',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify({company_id:ctx.companyId,title,description:text(input.description)||null,status:'todo',priority,due_at:input.dueAt||null,created_by:ctx.userId,source:'work_tasks',assignment_mode:assignmentMode})});const task=created[0];if(!task)throw new HttpError(502,'Не удалось создать задачу');const targetRows=rawTargets.map(t=>({company_id:ctx.companyId,task_id:task.id,target_type:text(t.targetType),target_value:text(t.targetValue)||null,target_label:text(t.targetLabel)||'Адресат'}));await db(env,'crm_task_targets',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify(targetRows)});const assignees=await resolveTargetUsers(env,ctx.companyId,rawTargets);if(assignmentMode==='individual'&&assignees.length){await db(env,'crm_task_executions',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify(assignees.map(id=>({company_id:ctx.companyId,task_id:task.id,user_id:id,status:'todo'})))});}return json({task:(await hydrate(env,ctx.companyId,[task],true))[0]},201);}
async function patchTask(request:Request,env:Env,id:string){const ctx=await context(request,env);const task=await readTask(env,ctx.companyId,id);const input=record(await request.json().catch(()=>({})));const admin=await canManage(request);const creator=text(task.created_by)===ctx.userId;const onlyStatus=Object.keys(input).every(key=>key==='status');if(!admin&&!creator){const recipients=await recipientUserIds(env,ctx.companyId,id);if(!onlyStatus||!recipients.includes(ctx.userId))throw new HttpError(403,'Изменять параметры задачи может постановщик или администратор');}const patch:Row={updated_at:new Date().toISOString()};if(input.status!==undefined){const value=text(input.status);if(!statuses.includes(value))throw new HttpError(400,'Некорректный статус');patch.status=value;patch.completed_at=value==='done'?new Date().toISOString():null;}if(input.title!==undefined)patch.title=text(input.title);if(input.description!==undefined)patch.description=text(input.description)||null;if(input.priority!==undefined)patch.priority=text(input.priority);if(input.dueAt!==undefined)patch.due_at=input.dueAt||null;const rows=await db<Row[]>(env,`crm_tasks?company_id=eq.${ctx.companyId}&id=eq.${id}`,{method:'PATCH',headers:{prefer:'return=representation'},body:JSON.stringify(patch)});return json({task:(await hydrate(env,ctx.companyId,[rows[0]||task],true))[0]});}
async function patchExecution(request:Request,env:Env,id:string){const ctx=await context(request,env);const task=await readTask(env,ctx.companyId,id);if(text(task.assignment_mode)!=='individual')throw new HttpError(400,'У задачи общий режим выполнения');const input=record(await request.json().catch(()=>({})));const status=text(input.status);if(!statuses.includes(status))throw new HttpError(400,'Некорректный статус');const rows=await db<Row[]>(env,`crm_task_executions?company_id=eq.${ctx.companyId}&task_id=eq.${id}&user_id=eq.${ctx.userId}`,{method:'PATCH',headers:{prefer:'return=representation'},body:JSON.stringify({status,completed_at:status==='done'?new Date().toISOString():null,updated_at:new Date().toISOString()})});if(!rows.length)throw new HttpError(403,'Задача не назначена вам персонально');const all=await db<Row[]>(env,`crm_task_executions?company_id=eq.${ctx.companyId}&task_id=eq.${id}&select=status`);const next=all.length&&all.every(r=>text(r.status)==='done')?'done':all.some(r=>text(r.status)==='in_progress')?'in_progress':all.some(r=>text(r.status)==='review')?'review':'todo';await db(env,`crm_tasks?company_id=eq.${ctx.companyId}&id=eq.${id}`,{method:'PATCH',headers:{prefer:'return=minimal'},body:JSON.stringify({status:next,completed_at:next==='done'?new Date().toISOString():null,updated_at:new Date().toISOString()})});return json({task:(await hydrate(env,ctx.companyId,[await readTask(env,ctx.companyId,id)],true))[0]});}
async function comment(request:Request,env:Env,id:string){const ctx=await context(request,env);await readTask(env,ctx.companyId,id);const input=record(await request.json().catch(()=>({})));const body=text(input.body);if(!body)throw new HttpError(400,'Комментарий пуст');await db(env,'crm_task_comments',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify({company_id:ctx.companyId,task_id:id,user_id:ctx.userId,body})});return json({task:(await hydrate(env,ctx.companyId,[await readTask(env,ctx.companyId,id)],true))[0]});}
export async function handleTasks(request:Request,env:Env,url:URL):Promise<Response|null>{if(!url.pathname.startsWith('/api/tasks'))return null;try{const ctx=await context(request,env);if(url.pathname==='/api/tasks/bootstrap'&&request.method==='GET')return json(await bootstrap(env,ctx.companyId));if(url.pathname==='/api/tasks'&&request.method==='GET')return list(request,env,url);if(url.pathname==='/api/tasks'&&request.method==='POST')return create(request,env);const match=url.pathname.match(/^\/api\/tasks\/([0-9a-f-]+)(?:\/(execution|comments))?$/i);if(!match||!uuid.test(match[1]))throw new HttpError(404,'Маршрут задач не найден');if(match[2]==='execution'&&request.method==='PATCH')return patchExecution(request,env,match[1]);if(match[2]==='comments'&&request.method==='POST')return comment(request,env,match[1]);if(!match[2]&&request.method==='PATCH')return patchTask(request,env,match[1]);return json({error:'Method not allowed'},405);}catch(error){if(error instanceof HttpError)return json({error:error.message},error.status);return json({error:error instanceof Error?error.message:String(error)},500);}}
