import { resolveCompanyId } from './companyContext';
import { listActiveCompanyUsers } from './companyUsers';
import type { Env } from './integrations';

type Row = Record<string, unknown>;
type Target = { targetType: 'all' | 'position' | 'job_title' | 'user'; targetValue?: string | null; targetLabel: string };

class SuiteError extends Error { constructor(readonly status:number,message:string){super(message);} }
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const record=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:{};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const userId=(request:Request)=>text(request.headers.get('x-amanat-auth-user'));
const role=(request:Request)=>text(request.headers.get('x-amanat-auth-role'));
const priorityScore=(value:unknown)=>({urgent:4,high:3,medium:2,low:1}[text(value) as 'urgent'|'high'|'medium'|'low']||0);

function headers(env:Env,extra:HeadersInit={}):HeadersInit{return{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json',...(extra as Record<string,string>)};}
async function db<T>(env:Env,path:string,init:RequestInit={}):Promise<T>{const response=await fetch(`${env.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/${path}`,{...init,headers:headers(env,init.headers||{})});const body=await response.text();if(!response.ok)throw new SuiteError(502,`Task suite database ${response.status}: ${body.slice(0,800)}`);return(body?JSON.parse(body):null)as T;}
async function context(request:Request,env:Env){const id=userId(request);if(!uuid.test(id))throw new SuiteError(401,'Не удалось определить пользователя');const requested=text(request.headers.get('x-imds-company-id'));const scoped=requested?{...env,CURRENT_COMPANY_ID:requested}:env;return{companyId:await resolveCompanyId(scoped,id),userId:id};}

async function companyUsers(env:Env,companyId:string){
  const users=await listActiveCompanyUsers(env,companyId,'id,name,email');
  const assignments=await db<Row[]>(env,`crm_access_user_assignments?company_id=eq.${companyId}&select=user_id,position_id,job_title`);
  const positions=await db<Row[]>(env,`crm_access_positions?company_id=eq.${companyId}&select=id,name,system_key`);
  const aMap=new Map(assignments.map(row=>[text(row.user_id),row]));
  const pMap=new Map(positions.map(row=>[text(row.id),row]));
  return users.map(row=>{const a=aMap.get(text(row.id))||{};const position=pMap.get(text(a.position_id));return{id:text(row.id),name:text(row.name)||text(row.email)||'Сотрудник',positionId:text(a.position_id)||null,positionName:text(position?.name)||null,positionKey:text(position?.system_key)||null,jobTitle:text(a.job_title)||null};});
}

async function callCenterTarget(env:Env,companyId:string):Promise<Target>{
  const positions=await db<Row[]>(env,`crm_access_positions?company_id=eq.${companyId}&system_key=eq.call_center&select=id,name&limit=1`);
  if(positions[0])return{targetType:'position',targetValue:text(positions[0].id),targetLabel:text(positions[0].name)||'Колл-центр'};
  return{targetType:'all',targetLabel:'Всем сотрудникам'};
}

function targetMatches(target:Row,user:{id:string;positionId:string|null;jobTitle:string|null}){
  const type=text(target.target_type);const value=text(target.target_value);
  return type==='all'||(type==='user'&&value===user.id)||(type==='position'&&value===user.positionId)||(type==='job_title'&&value===user.jobTitle);
}

async function nextTask(request:Request,env:Env){
  const ctx=await context(request,env);const users=await companyUsers(env,ctx.companyId);const me=users.find(u=>u.id===ctx.userId);if(!me)throw new SuiteError(403,'Пользователь не активен');
  const mine=await db<Row[]>(env,`crm_tasks?company_id=eq.${ctx.companyId}&source=eq.work_tasks&queue_claimed_by=eq.${ctx.userId}&status=not.in.(done,cancelled)&select=id&order=queue_claimed_at.asc&limit=1`);
  if(mine[0])return json({taskId:text(mine[0].id),reused:true});
  const tasks=await db<Row[]>(env,`crm_tasks?company_id=eq.${ctx.companyId}&source=eq.work_tasks&queue_claimed_by=is.null&status=not.in.(done,cancelled)&select=id,priority,due_at,created_at&limit=300`);
  if(!tasks.length)return json({taskId:null});
  const ids=tasks.map(t=>text(t.id)).filter(Boolean);
  const targets=await db<Row[]>(env,`crm_task_targets?company_id=eq.${ctx.companyId}&task_id=in.(${ids.join(',')})&select=task_id,target_type,target_value`);
  const eligible=tasks.filter(task=>targets.some(target=>text(target.task_id)===text(task.id)&&targetMatches(target,me))).sort((a,b)=>{
    const p=priorityScore(b.priority)-priorityScore(a.priority);if(p)return p;
    const ad=a.due_at?new Date(String(a.due_at)).getTime():Number.MAX_SAFE_INTEGER;const bd=b.due_at?new Date(String(b.due_at)).getTime():Number.MAX_SAFE_INTEGER;if(ad!==bd)return ad-bd;
    return new Date(String(a.created_at)).getTime()-new Date(String(b.created_at)).getTime();
  });
  for(const candidate of eligible.slice(0,20)){
    const claimed=await db<Row[]>(env,`crm_tasks?company_id=eq.${ctx.companyId}&id=eq.${text(candidate.id)}&queue_claimed_by=is.null`,{method:'PATCH',headers:{prefer:'return=representation'},body:JSON.stringify({queue_claimed_by:ctx.userId,queue_claimed_at:new Date().toISOString(),accepted_at:new Date().toISOString(),updated_at:new Date().toISOString()})});
    if(claimed[0]){await db(env,'crm_task_history',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify({company_id:ctx.companyId,task_id:candidate.id,actor_id:ctx.userId,event_type:'queue_claimed',to_value:ctx.userId,meta:{source:'next_task'}})});return json({taskId:text(candidate.id),reused:false});}
  }
  return json({taskId:null});
}

const builtInTemplates=[
  {id:'builtin:callback',name:'Перезвонить клиенту',description:'Связаться с клиентом, уточнить запрос и зафиксировать результат.',workflowKey:'call_center',priority:'high',dueOffsetMinutes:30,slaMinutes:10,assignmentMode:'shared',checklist:['Открыть карточку клиента','Позвонить','Зафиксировать результат']},
  {id:'builtin:confirm',name:'Подтвердить запись',description:'Связаться с пациентом и подтвердить предстоящую запись.',workflowKey:'call_center',priority:'high',dueOffsetMinutes:120,slaMinutes:30,assignmentMode:'shared',checklist:['Проверить дату и врача','Связаться с пациентом','Зафиксировать подтверждение']},
  {id:'builtin:whatsapp',name:'Ответить в WhatsApp',description:'Ответить клиенту в WhatsApp и довести диалог до следующего действия.',workflowKey:'call_center',priority:'urgent',dueOffsetMinutes:10,slaMinutes:5,assignmentMode:'shared',checklist:['Открыть диалог','Ответить','Зафиксировать результат']},
  {id:'builtin:campaign',name:'Запустить рекламную кампанию',description:'Подготовить материалы, проверить настройки и запустить кампанию.',workflowKey:'marketing',priority:'high',dueOffsetMinutes:1440,slaMinutes:null,assignmentMode:'shared',checklist:['Проверить оффер','Проверить креативы','Проверить аудиторию','Запустить','Проверить события']},
  {id:'builtin:reels',name:'Подготовить Reels',description:'Подготовить ролик от идеи до публикации.',workflowKey:'content',priority:'medium',dueOffsetMinutes:2880,slaMinutes:null,assignmentMode:'shared',checklist:['Сценарий','Съёмка','Монтаж','Согласование','Публикация']},
] as const;

function templateDto(row:Row){return{id:text(row.id),name:text(row.name),description:row.description||null,workflowKey:text(row.workflow_key)||'general',priority:text(row.priority)||'medium',dueOffsetMinutes:Number(row.due_offset_minutes)||null,slaMinutes:Number(row.sla_minutes)||null,assignmentMode:text(row.assignment_mode)==='individual'?'individual':'shared',targets:Array.isArray(row.targets)?row.targets:[],checklist:Array.isArray(row.checklist)?row.checklist:[],linkType:row.link_type||null,builtin:false};}
async function templates(request:Request,env:Env){const ctx=await context(request,env);if(request.method==='GET'){const rows=await db<Row[]>(env,`crm_task_templates?company_id=eq.${ctx.companyId}&is_active=eq.true&select=*&order=created_at.desc`);return json({templates:[...builtInTemplates.map(item=>({...item,builtin:true,targets:[]})),...rows.map(templateDto)]});}if(request.method==='POST'){const input=record(await request.json().catch(()=>({})));const name=text(input.name);if(name.length<2)throw new SuiteError(400,'Укажите название шаблона');const rows=await db<Row[]>(env,'crm_task_templates',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify({company_id:ctx.companyId,name,description:text(input.description)||null,workflow_key:text(input.workflowKey)||'general',priority:text(input.priority)||'medium',due_offset_minutes:Number(input.dueOffsetMinutes)||null,sla_minutes:Number(input.slaMinutes)||null,assignment_mode:text(input.assignmentMode)==='individual'?'individual':'shared',targets:Array.isArray(input.targets)?input.targets:[],checklist:Array.isArray(input.checklist)?input.checklist:[],link_type:text(input.linkType)||null,created_by:ctx.userId})});return json({template:templateDto(rows[0]||{})},201);}return json({error:'Method not allowed'},405);}

async function patchTemplate(request:Request,env:Env,id:string){const ctx=await context(request,env);if(request.method!=='DELETE'&&request.method!=='PATCH')return json({error:'Method not allowed'},405);const input=request.method==='PATCH'?record(await request.json().catch(()=>({}))):{};const patch:Row={updated_at:new Date().toISOString()};if(request.method==='DELETE')patch.is_active=false;else{if(input.name!==undefined)patch.name=text(input.name);if(input.description!==undefined)patch.description=text(input.description)||null;if(input.workflowKey!==undefined)patch.workflow_key=text(input.workflowKey);if(input.priority!==undefined)patch.priority=text(input.priority);if(input.dueOffsetMinutes!==undefined)patch.due_offset_minutes=Number(input.dueOffsetMinutes)||null;if(input.slaMinutes!==undefined)patch.sla_minutes=Number(input.slaMinutes)||null;if(input.targets!==undefined)patch.targets=Array.isArray(input.targets)?input.targets:[];if(input.checklist!==undefined)patch.checklist=Array.isArray(input.checklist)?input.checklist:[];}
 const rows=await db<Row[]>(env,`crm_task_templates?company_id=eq.${ctx.companyId}&id=eq.${id}`,{method:'PATCH',headers:{prefer:'return=representation'},body:JSON.stringify(patch)});if(!rows[0])throw new SuiteError(404,'Шаблон не найден');return json({template:templateDto(rows[0])});}

const automationDefaults=[
 {key:'new_lead_followup',name:'Новый лид без ответа',description:'Через 15 минут создаёт срочную задачу колл-центру, если по новому лиду ещё нет первого ответа.',config:{afterMinutes:15}},
 {key:'missed_call',name:'Пропущенный звонок',description:'Создаёт задачу перезвонить по входящему звонку без ответа.',config:{afterMinutes:2}},
 {key:'whatsapp_unanswered',name:'WhatsApp без ответа',description:'Если в WhatsApp остаются непрочитанные сообщения дольше 10 минут, создаёт задачу на ответ.',config:{afterMinutes:10}},
 {key:'appointment_confirmation',name:'Подтверждение записи',description:'За сутки до записи создаёт задачу подтвердить визит пациента.',config:{beforeHours:24}},
] as const;

async function ensureAutomationRules(env:Env,companyId:string){const existing=await db<Row[]>(env,`crm_task_automation_rules?company_id=eq.${companyId}&select=*`);const keys=new Set(existing.map(r=>text(r.key)));for(const item of automationDefaults){if(keys.has(item.key))continue;await db(env,'crm_task_automation_rules',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify({company_id:companyId,key:item.key,name:item.name,description:item.description,enabled:true,config:item.config})});}return db<Row[]>(env,`crm_task_automation_rules?company_id=eq.${companyId}&select=*&order=created_at.asc`);}
function ruleDto(row:Row){return{id:text(row.id),key:text(row.key),name:text(row.name),description:row.description||null,enabled:Boolean(row.enabled),config:record(row.config),lastRunAt:row.last_run_at||null};}
async function automations(request:Request,env:Env){const ctx=await context(request,env);if(request.method==='GET')return json({rules:(await ensureAutomationRules(env,ctx.companyId)).map(ruleDto)});if(request.method==='PATCH'){if(role(request)!=='administrator')throw new SuiteError(403,'Настройки автоматизаций доступны администратору');const input=record(await request.json().catch(()=>({})));const key=text(input.key);const patch:Row={updated_at:new Date().toISOString()};if(input.enabled!==undefined)patch.enabled=Boolean(input.enabled);if(input.config!==undefined)patch.config=record(input.config);const rows=await db<Row[]>(env,`crm_task_automation_rules?company_id=eq.${ctx.companyId}&key=eq.${encodeURIComponent(key)}`,{method:'PATCH',headers:{prefer:'return=representation'},body:JSON.stringify(patch)});if(!rows[0])throw new SuiteError(404,'Автоматизация не найдена');return json({rule:ruleDto(rows[0])});}return json({error:'Method not allowed'},405);}

async function insertAutomationTask(env:Env,companyId:string,key:string,eventKey:string,payload:{title:string;description?:string;priority?:string;workflowKey?:string;dueAt?:string|null;slaMinutes?:number|null;linkType?:string;linkId?:string;linkLabel?:string;target:Target}){
 const exists=await db<Row[]>(env,`crm_tasks?company_id=eq.${companyId}&automation_key=eq.${encodeURIComponent(key)}&automation_event_key=eq.${encodeURIComponent(eventKey)}&select=id&limit=1`);if(exists[0])return false;
 const workflowKey=payload.workflowKey||'call_center';const stageKey=workflowKey==='call_center'?'new':'todo';const slaMinutes=payload.slaMinutes||null;
 const response=await fetch(`${env.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/crm_tasks`,{method:'POST',headers:headers(env,{prefer:'return=representation'}),body:JSON.stringify({company_id:companyId,title:payload.title,description:payload.description||null,status:'todo',stage_key:stageKey,workflow_key:workflowKey,priority:payload.priority||'high',due_at:payload.dueAt||null,sla_minutes:slaMinutes,sla_due_at:slaMinutes?new Date(Date.now()+slaMinutes*60000).toISOString():null,source:'work_tasks',assignment_mode:'shared',link_type:payload.linkType||null,link_id:payload.linkId||null,link_label:payload.linkLabel||null,automation_key:key,automation_event_key:eventKey})});
 if(response.status===409)return false;const body=await response.text();if(!response.ok)throw new SuiteError(502,`Automation task insert ${response.status}: ${body.slice(0,500)}`);const rows=body?JSON.parse(body) as Row[]:[];const task=rows[0];if(!task)return false;
 await db(env,'crm_task_targets',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify({company_id:companyId,task_id:task.id,target_type:payload.target.targetType,target_value:payload.target.targetValue||null,target_label:payload.target.targetLabel})});
 await db(env,'crm_task_history',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify({company_id:companyId,task_id:task.id,event_type:'automation_created',to_value:key,meta:{eventKey}})});return true;
}

async function runCompanyAutomations(env:Env,companyId:string){const rules=(await ensureAutomationRules(env,companyId)).filter(r=>Boolean(r.enabled));const target=await callCenterTarget(env,companyId);let created=0;const now=Date.now();
 for(const rule of rules){const key=text(rule.key);const config=record(rule.config);
  if(key==='new_lead_followup'){const minutes=Number(config.afterMinutes)||15;const before=new Date(now-minutes*60000).toISOString();const leads=await db<Row[]>(env,`marketing_leads?company_id=eq.${companyId}&first_response_at=is.null&created_at=lt.${encodeURIComponent(before)}&select=id,name,phone,source,created_at&order=created_at.desc&limit=100`);for(const lead of leads){if(await insertAutomationTask(env,companyId,key,text(lead.id),{title:`Связаться с новым лидом${text(lead.name)?`: ${text(lead.name)}`:''}`,description:`Лид ожидает первого ответа более ${minutes} минут.${text(lead.phone)?` Телефон: ${text(lead.phone)}`:''}`,priority:'urgent',workflowKey:'call_center',dueAt:new Date(now+10*60000).toISOString(),slaMinutes:5,linkType:'lead',linkId:text(lead.id),linkLabel:text(lead.name)||text(lead.phone)||'Новый лид',target}))created++;}}
  if(key==='missed_call'){const minutes=Number(config.afterMinutes)||2;const before=new Date(now-minutes*60000).toISOString();const calls=await db<Row[]>(env,`marketing_calls?company_id=eq.${companyId}&call_direction=eq.inbound&answered_at=is.null&started_at=lt.${encodeURIComponent(before)}&select=id,client_name,client_phone,started_at&order=started_at.desc&limit=100`);for(const call of calls){if(await insertAutomationTask(env,companyId,key,text(call.id),{title:`Перезвонить после пропущенного звонка${text(call.client_name)?`: ${text(call.client_name)}`:''}`,description:text(call.client_phone)?`Телефон: ${text(call.client_phone)}`:'Пропущенный входящий звонок.',priority:'urgent',workflowKey:'call_center',dueAt:new Date(now+10*60000).toISOString(),slaMinutes:10,linkType:'call',linkId:text(call.id),linkLabel:text(call.client_name)||text(call.client_phone)||'Пропущенный звонок',target}))created++;}}
  if(key==='whatsapp_unanswered'){const minutes=Number(config.afterMinutes)||10;const before=new Date(now-minutes*60000).toISOString();const chats=await db<Row[]>(env,`marketing_conversations?company_id=eq.${companyId}&channel=ilike.*whatsapp*&unread_count=gt.0&last_message_at=lt.${encodeURIComponent(before)}&archived_at=is.null&select=id,title,phone,last_message_at,unread_count&order=last_message_at.desc&limit=100`);for(const chat of chats){if(await insertAutomationTask(env,companyId,key,text(chat.id),{title:`Ответить в WhatsApp${text(chat.title)?`: ${text(chat.title)}`:''}`,description:`Диалог ждёт ответа более ${minutes} минут. Непрочитано: ${Number(chat.unread_count)||1}.`,priority:'urgent',workflowKey:'call_center',dueAt:new Date(now+5*60000).toISOString(),slaMinutes:5,linkType:'whatsapp',linkId:text(chat.id),linkLabel:text(chat.title)||text(chat.phone)||'WhatsApp',target}))created++;}}
  if(key==='appointment_confirmation'){const hours=Number(config.beforeHours)||24;const from=new Date(now+(hours-1)*3600000).toISOString();const to=new Date(now+(hours+1)*3600000).toISOString();const appointments=await db<Row[]>(env,`waba_clinic_appointments?company_id=eq.${companyId}&starts_at=gte.${encodeURIComponent(from)}&starts_at=lte.${encodeURIComponent(to)}&status=not.in.(cancelled,canceled)&select=id,patient_name,phone,starts_at&order=starts_at.asc&limit=100`);for(const appointment of appointments){if(await insertAutomationTask(env,companyId,key,text(appointment.id),{title:`Подтвердить запись${text(appointment.patient_name)?`: ${text(appointment.patient_name)}`:''}`,description:`Запись: ${new Date(String(appointment.starts_at)).toLocaleString('ru-RU')}.${text(appointment.phone)?` Телефон: ${text(appointment.phone)}`:''}`,priority:'high',workflowKey:'call_center',dueAt:new Date(new Date(String(appointment.starts_at)).getTime()-2*3600000).toISOString(),slaMinutes:30,linkType:'appointment',linkId:text(appointment.id),linkLabel:text(appointment.patient_name)||text(appointment.phone)||'Запись',target}))created++;}}
  await db(env,`crm_task_automation_rules?company_id=eq.${companyId}&id=eq.${text(rule.id)}`,{method:'PATCH',headers:{prefer:'return=minimal'},body:JSON.stringify({last_run_at:new Date().toISOString()})});
 }
 return created;}

export async function runTaskAutomationScan(env:Env){const companies=await db<Row[]>(env,'crm_companies?select=id&limit=500');let created=0;for(const company of companies){try{created+=await runCompanyAutomations(env,text(company.id));}catch(error){console.error('Task automation company scan failed',text(company.id),error);}}return{companies:companies.length,created};}

async function analytics(request:Request,env:Env){const ctx=await context(request,env);const [tasks,users,targets,executions]=await Promise.all([db<Row[]>(env,`crm_tasks?company_id=eq.${ctx.companyId}&source=eq.work_tasks&select=id,status,priority,due_at,sla_due_at,created_at,completed_at,workflow_key,assignment_mode&limit=2000`),companyUsers(env,ctx.companyId),db<Row[]>(env,`crm_task_targets?company_id=eq.${ctx.companyId}&select=task_id,target_type,target_value`),db<Row[]>(env,`crm_task_executions?company_id=eq.${ctx.companyId}&select=task_id,user_id,status,completed_at`)]);const now=Date.now();const open=tasks.filter(t=>!['done','cancelled'].includes(text(t.status)));const done=tasks.filter(t=>text(t.status)==='done');const overdue=open.filter(t=>t.due_at&&new Date(String(t.due_at)).getTime()<now);const slaBreached=open.filter(t=>t.sla_due_at&&new Date(String(t.sla_due_at)).getTime()<now);const durations=done.filter(t=>t.completed_at&&t.created_at).map(t=>(new Date(String(t.completed_at)).getTime()-new Date(String(t.created_at)).getTime())/3600000).filter(v=>v>=0&&Number.isFinite(v));const byWorkflow=new Map<string,{workflowKey:string;open:number;done:number;overdue:number}>();for(const task of tasks){const key=text(task.workflow_key)||'general';const row=byWorkflow.get(key)||{workflowKey:key,open:0,done:0,overdue:0};if(text(task.status)==='done')row.done++;else if(text(task.status)!=='cancelled')row.open++;if(task.due_at&&new Date(String(task.due_at)).getTime()<now&&!['done','cancelled'].includes(text(task.status)))row.overdue++;byWorkflow.set(key,row);}const byUser=users.map(user=>{const taskIds=new Set<string>();for(const target of targets)if(targetMatches(target,user))taskIds.add(text(target.task_id));for(const execution of executions)if(text(execution.user_id)===user.id)taskIds.add(text(execution.task_id));const owned=tasks.filter(t=>taskIds.has(text(t.id)));return{userId:user.id,userName:user.name,open:owned.filter(t=>!['done','cancelled'].includes(text(t.status))).length,overdue:owned.filter(t=>t.due_at&&new Date(String(t.due_at)).getTime()<now&&!['done','cancelled'].includes(text(t.status))).length,done:owned.filter(t=>text(t.status)==='done').length};}).sort((a,b)=>b.open-a.open);return json({summary:{total:tasks.length,open:open.length,done:done.length,overdue:overdue.length,slaBreached:slaBreached.length,averageCompletionHours:durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length*10)/10:null},byUser,byWorkflow:[...byWorkflow.values()]});}

async function followUp(request:Request,env:Env){const ctx=await context(request,env);const input=record(await request.json().catch(()=>({})));const sourceTaskId=text(input.taskId);if(!uuid.test(sourceTaskId))throw new SuiteError(400,'Некорректная задача');const source=(await db<Row[]>(env,`crm_tasks?company_id=eq.${ctx.companyId}&id=eq.${sourceTaskId}&select=*&limit=1`))[0];if(!source)throw new SuiteError(404,'Задача не найдена');const targets=await db<Row[]>(env,`crm_task_targets?company_id=eq.${ctx.companyId}&task_id=eq.${sourceTaskId}&select=target_type,target_value,target_label`);const when=text(input.when)||new Date(Date.now()+30*60000).toISOString();const title=text(input.title)||`Повторно: ${text(source.title)}`;const rows=await db<Row[]>(env,'crm_tasks',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify({company_id:ctx.companyId,title,description:`Автоматическое следующее действие по задаче «${text(source.title)}».`,status:'todo',stage_key:text(source.workflow_key)==='call_center'?'new':'todo',workflow_key:text(source.workflow_key)||'general',priority:text(source.priority)||'medium',due_at:when,created_by:ctx.userId,source:'work_tasks',assignment_mode:'shared',link_type:source.link_type||null,link_id:source.link_id||null,link_label:source.link_label||null})});const task=rows[0];if(!task)throw new SuiteError(502,'Не удалось создать следующее действие');if(targets.length)await db(env,'crm_task_targets',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify(targets.map(t=>({company_id:ctx.companyId,task_id:task.id,target_type:t.target_type,target_value:t.target_value||null,target_label:t.target_label||'Адресат'})))});await db(env,'crm_task_history',{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify({company_id:ctx.companyId,task_id:task.id,actor_id:ctx.userId,event_type:'follow_up_created',from_value:sourceTaskId,meta:{sourceResult:text(source.result_code)}})});return json({taskId:text(task.id)},201);}

export async function handleTaskSuite(request:Request,env:Env,url:URL):Promise<Response|null>{if(!url.pathname.startsWith('/api/tasks/suite'))return null;try{if(url.pathname==='/api/tasks/suite/next'&&request.method==='POST')return nextTask(request,env);if(url.pathname==='/api/tasks/suite/templates')return templates(request,env);const template=url.pathname.match(/^\/api\/tasks\/suite\/templates\/([0-9a-f-]+)$/i);if(template)return patchTemplate(request,env,template[1]);if(url.pathname==='/api/tasks/suite/analytics'&&request.method==='GET')return analytics(request,env);if(url.pathname==='/api/tasks/suite/automations')return automations(request,env);if(url.pathname==='/api/tasks/suite/follow-up'&&request.method==='POST')return followUp(request,env);if(url.pathname==='/api/tasks/suite/run-automations'&&request.method==='POST'){if(role(request)!=='administrator')throw new SuiteError(403,'Доступно только администратору');const ctx=await context(request,env);return json({created:await runCompanyAutomations(env,ctx.companyId)});}return json({error:'Method not allowed'},405);}catch(error){if(error instanceof SuiteError)return json({error:error.message},error.status);return json({error:error instanceof Error?error.message:String(error)},500);}}
