import type { UniversalTelephonyEnv } from './telephonyGateway';
import { requireCompanyId } from './tenantScope';

type Row = Record<string, unknown>;
type Provider = 'asterisk' | 'freepbx' | 'twilio' | 'voximplant';
type Definition = { required: string[]; secrets: string[]; mapping: Record<string, keyof UniversalTelephonyEnv> };
const definitions: Record<Provider, Definition> = {
  asterisk: { required: ['ariBaseUrl','ariUsername','ariPassword','stasisApp','endpointTemplate'], secrets: ['ariPassword'], mapping: { ariBaseUrl:'ASTERISK_ARI_BASE_URL', ariUsername:'ASTERISK_ARI_USERNAME', ariPassword:'ASTERISK_ARI_PASSWORD', stasisApp:'ASTERISK_STASIS_APP', endpointTemplate:'ASTERISK_ENDPOINT_TEMPLATE', callerId:'ASTERISK_CALLER_ID' } },
  freepbx: { required: ['ariBaseUrl','ariUsername','ariPassword','stasisApp','endpointTemplate'], secrets: ['ariPassword'], mapping: { ariBaseUrl:'FREEPBX_ARI_BASE_URL', ariUsername:'FREEPBX_ARI_USERNAME', ariPassword:'FREEPBX_ARI_PASSWORD', stasisApp:'FREEPBX_STASIS_APP', endpointTemplate:'FREEPBX_ENDPOINT_TEMPLATE', callerId:'FREEPBX_CALLER_ID' } },
  twilio: { required: ['accountSid','authToken','fromNumber','agentEndpoint'], secrets: ['authToken'], mapping: { accountSid:'TWILIO_ACCOUNT_SID', authToken:'TWILIO_AUTH_TOKEN', fromNumber:'TWILIO_FROM_NUMBER', agentEndpoint:'TWILIO_AGENT_ENDPOINT' } },
  voximplant: { required: ['accountId','keyId','privateKey','ruleId'], secrets: ['privateKey'], mapping: { accountId:'VOXIMPLANT_ACCOUNT_ID', keyId:'VOXIMPLANT_KEY_ID', privateKey:'VOXIMPLANT_PRIVATE_KEY', ruleId:'VOXIMPLANT_RULE_ID', controlProtocol:'VOXIMPLANT_CONTROL_PROTOCOL' } },
};
const text=(v:unknown)=>typeof v==='string'?v.trim():v==null?'':String(v).trim();
const rec=(v:unknown):Row=>v&&typeof v==='object'&&!Array.isArray(v)?v as Row:{};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
function headers(env:UniversalTelephonyEnv,extra:HeadersInit={}){const h=new Headers(extra);h.set('apikey',env.SUPABASE_SERVICE_ROLE_KEY);h.set('authorization',`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`);h.set('accept','application/json');if(!h.has('content-type'))h.set('content-type','application/json');return h;}
async function db<T>(env:UniversalTelephonyEnv,path:string,init:RequestInit={}):Promise<T>{const r=await fetch(`${env.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/${path}`,{...init,headers:headers(env,init.headers),cache:'no-store'});const raw=await r.text();if(!r.ok)throw new Error(`Telephony credentials ${r.status}: ${raw.slice(0,800)}`);return(raw?JSON.parse(raw):null)as T;}
function secret(env:UniversalTelephonyEnv){const direct=text((env as unknown as Row).INTEGRATION_ENCRYPTION_KEY);return direct||`amanat-integrations:v1:${env.SUPABASE_SERVICE_ROLE_KEY}`;}
function b64(bytes:Uint8Array){let out='';for(const b of bytes)out+=String.fromCharCode(b);return btoa(out);}
function fromB64(v:string){const raw=atob(v);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
async function key(value:string){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return crypto.subtle.importKey('raw',hash,{name:'AES-GCM'},false,['encrypt','decrypt']);}
async function encrypt(payload:Row,value:string){const iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(value),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(JSON.stringify(payload)));return{encrypted_payload:b64(new Uint8Array(data)),iv:b64(iv)};}
async function decrypt(row:Row,value:string):Promise<Row>{const k=await key(value),data=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64(text(row.iv))},k,fromB64(text(row.encrypted_payload)));return rec(JSON.parse(new TextDecoder().decode(data)));}
function provider(value:unknown):Provider|null{const p=text(value).toLowerCase();return p in definitions?p as Provider:null;}
async function rows(env:UniversalTelephonyEnv){const companyId=requireCompanyId(env);return db<Row[]>(env,`integration_credentials?company_id=eq.${encodeURIComponent(companyId)}&user_id=is.null&provider=in.(asterisk,freepbx,twilio,voximplant)&select=*`);}
function summary(row:Row){return{provider:text(row.provider),configured:true,status:text(row.status)||'configured',values:rec(rec(row.config_summary).values),secretFields:rec(rec(row.config_summary).secretFields),lastVerifiedAt:row.last_verified_at||null,lastError:row.last_error||null};}
export async function hydrateTelephonyProviderEnv<T extends UniversalTelephonyEnv>(env:T):Promise<T>{const result={...env} as T;for(const row of await rows(env)){const p=provider(row.provider);if(!p)continue;try{const payload=await decrypt(row,secret(env)),def=definitions[p];for(const [field,target] of Object.entries(def.mapping)){const value=text(payload[field]);if(value)(result as Record<string,unknown>)[target]=value;}}catch(error){console.error(`Unable to decrypt ${p} telephony credentials`,error);}}return result;}
export async function handleTelephonyProviderConfig(request:Request,env:UniversalTelephonyEnv,url:URL):Promise<Response|null>{if(!url.pathname.startsWith('/api/telephony/providers'))return null;if(text(request.headers.get('x-amanat-auth-role')).toLowerCase()!=='administrator')return json({error:'Настройки телефонии доступны только администратору'},403);const companyId=requireCompanyId(env);if(url.pathname==='/api/telephony/providers'&&request.method==='GET')return json({providers:(await rows(env)).map(summary)});const p=provider(url.pathname.split('/').pop());if(!p)return json({error:'Неизвестный telephony provider'},404);const existing=(await db<Row[]>(env,`integration_credentials?company_id=eq.${encodeURIComponent(companyId)}&user_id=is.null&provider=eq.${p}&select=*&limit=1`))[0]||null;if(request.method==='GET')return json({provider:existing?summary(existing):{provider:p,configured:false}});if(request.method==='DELETE'){await db(env,`integration_credentials?company_id=eq.${encodeURIComponent(companyId)}&user_id=is.null&provider=eq.${p}`,{method:'DELETE',headers:{prefer:'return=minimal'}});return json({ok:true,provider:p});}if(request.method!=='PUT')return json({error:'Method not allowed'},405);const incoming=rec(await request.json().catch(()=>({}))),def=definitions[p];let payload:Row={};if(existing)try{payload=await decrypt(existing,secret(env));}catch{payload={};}for(const field of Object.keys(def.mapping)){const value=text(incoming[field]);if(value)payload[field]=value;else if(!def.secrets.includes(field)&&field in incoming)payload[field]=incoming[field];}const missing=def.required.filter(field=>!text(payload[field]));if(missing.length)return json({error:`Заполните обязательные поля: ${missing.join(', ')}`},400);const sealed=await encrypt(payload,secret(env)),values:Record<string,string>={},secretFields:Record<string,boolean>={};for(const field of Object.keys(def.mapping)){if(def.secrets.includes(field))secretFields[field]=Boolean(text(payload[field]));else values[field]=text(payload[field]);}const stored={provider:p,company_id:companyId,user_id:null,...sealed,config_summary:{values,secretFields},status:'configured',last_error:null,updated_at:new Date().toISOString()};const saved=existing?.id?await db<Row[]>(env,`integration_credentials?id=eq.${encodeURIComponent(text(existing.id))}&company_id=eq.${encodeURIComponent(companyId)}`,{method:'PATCH',headers:{prefer:'return=representation'},body:JSON.stringify(stored)}):await db<Row[]>(env,'integration_credentials',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify(stored)});if(incoming.activate===true)await db(env,`telephony_settings?company_id=eq.${encodeURIComponent(companyId)}`,{method:'PATCH',body:JSON.stringify({provider:p,updated_at:new Date().toISOString()})});return json({ok:true,provider:summary(saved[0]||stored),active:incoming.activate===true});}
